title: rasjani @ github.io
email: jani.mikkonen@gmail.com
description: code - do we need something else?
url: https://rasjani.github.io
theme: jekyll-theme-hacker
linkedin_username: mikkonenjani
github_username:  rasjani
google_analytics: 
plugins:
  - jekyll-mentions
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll-relative-links
markdown: kramdown
highlighter: rouge
paginate: 15
paginate_path: "/blog/page:num/"
repository: rasjani/rasjani.github.io
collections:
  projects:
    output: true
    permalink: /projects/:path/


 
