title: rasjani @ github.io
description: code - do we need something else?
google_analytics: 
show_downloads: false
theme: jekyll-theme-hacker

gems:
  - jekyll-mentions
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll-relative-links

